// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/jmrflora/blogx/modelos"
	"strconv"
)

func Uploadartigo(id int, categorias []modelos.Categoria) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"d-flex justify-content-center\"><div class=\"w-75\"><form hx-encoding=\"multipart/form-data\" hx-post=\"/upload\" hx-target=\"#corpo\" hx-swap=\"innerHTML\"><textarea name=\"texto\" id=\"txt\"></textarea><div class=\"input-group\"><button type=\"button\" class=\"btn dropdown-toggle w-100\" data-bs-auto-close=\"outside\" data-bs-toggle=\"dropdown\">categorias</button><ul class=\"dropdown-menu w-100\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, categoria := range categorias {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<li><input class=\"form-check-input\" type=\"checkbox\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(categoria.Id))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/partials/uploadartigo.templ`, Line: 28, Col: 90}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"CategoriasIds\"> <label clas=\"form-check-label\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(categoria.NomeCategoria)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/partials/uploadartigo.templ`, Line: 29, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul></div><input class=\"btn btn-primary\" type=\"submit\" value=\"Submit\"></form></div><button _=\"on click call changeTextareaValue() then js htmx.trigger(&#39;#txt&#39;, &#39;myevent&#39;) end\">Click me.</button></div><script id=\"footer\" hx-swap-oob=\"beforeend\" src=\"https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js\"></script><script>\n    var simplemde = new SimpleMDE();\n\n    htmx.on(\"htmx:beforeSend\", function(evt){\n      var textarea = document.getElementById('txt');\n      textarea.value = simplemde.value();\n    })\n\n    function changeTextareaValue() {\n      console.log(\"to aqui\")\n      var textarea = document.getElementById('txt');\n      textarea.value = simplemde.value();\n    }\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
